# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputNomeEquipe = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNomeEquipe.setObjectName("inputNomeEquipe")
        self.verticalLayout.addWidget(self.inputNomeEquipe)
        self.inputMembros = QtWidgets.QTextEdit(self.centralwidget)
        self.inputMembros.setObjectName("inputMembros")
        self.verticalLayout.addWidget(self.inputMembros)
        self.btnCadastrarEquipe = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrarEquipe.setObjectName("btnCadastrarEquipe")
        self.verticalLayout.addWidget(self.btnCadastrarEquipe)
        self.btnCadastrarProva = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrarProva.setObjectName("btnCadastrarProva")
        self.verticalLayout.addWidget(self.btnCadastrarProva)
        self.btnVisualizarResultados = QtWidgets.QPushButton(self.centralwidget)
        self.btnVisualizarResultados.setObjectName("btnVisualizarResultados")
        self.verticalLayout.addWidget(self.btnVisualizarResultados)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Competições"))
        self.inputNomeEquipe.setPlaceholderText(_translate("MainWindow", "Digite o nome da equipe"))
        self.inputMembros.setPlaceholderText(_translate("MainWindow", "Digite os membros da equipe (um por linha)"))
        self.btnCadastrarEquipe.setText(_translate("MainWindow", "Cadastrar Equipe"))
        self.btnCadastrarProva.setText(_translate("MainWindow", "Cadastrar Prova"))
        self.btnVisualizarResultados.setText(_translate("MainWindow", "Visualizar Resultados"))
